### PR TITLE
add crc16 kermit

### PR DESCRIPTION
**Pull request by niftytushar**
Hey, I have added a method to calculate crc16 kermit. It is similar to your `ccitt_16` method, so most of the code remains the same, just some minor changes to the crc table and calculation.

Added test cases and verified on http://www.sunshine2k.de/coding/javascript/crc/crc_js.html(http://www.sunshine2k.de/coding/javascript/crc/crc_js.html).
Works for me!

### CODE REVIEW

**Comment by TattdCodeMonkey** [comment]
👀 👍

**Comment by TattdCodeMonkey** [comment]
@niftytushar Thanks for the PR, `v0.6.0` has been tagged and published to [hex.pm](https://hex.pm/packages/crc/0.6.0)

**Comment by TattdCodeMonkey** [comment]
🤔 @niftytushar The two sites I use to sanity check are conflicting... 
for `123456789`
https://www.lammertbies.nl/comm/info/crc-calculation.html
`0x8921`
http://www.sunshine2k.de/coding/javascript/crc/crc_js.html
`0x2189`
¯\_(ツ)_/¯ why but I'm assuming `0x2189` you added is right.

**Comment by niftytushar** [comment]
That might be because CRC 16 Kermit uses reflected checksum and the result is in big endian format. The result obtained from http://www.sunshine2k.de/coding/javascript/crc/crc_js.html(http://www.sunshine2k.de/coding/javascript/crc/crc_js.html) is correct since it uses big endian format for Kermit, while https://www.lammertbies.nl/comm/info/crc-calculation.html(https://www.lammertbies.nl/comm/info/crc-calculation.html) uses little endian for all cases.

**Pull request merged**
