### PR TITLE
Fix elixir compiler warnings

### PR DESCRIPTION
**Pull request by seletz**
This PR fixes Elixir compiler warnings:

```
warning: extra parentheses on a bitstring specifier "binary()" have been deprecated. Please remove the parentheses: "binary"
warning: use Mix.Config is deprecated. Use the Config module instead
warning: use Bitwise is deprecated. import Bitwise instead
warning: ^^^ is deprecated. It is typically used as xor but it has the wrong precedence, use Bitwise.bxor/2 instead
```

### CODE REVIEW

**Comment by seletz** [comment]
@TattdCodeMonkey I updated the CI WF to do a matrix build against Elixir 1.14.5 / 1.15 and OTP25, 26.  Tested on my GH repo, seems to pass.

**Comment by TattdCodeMonkey** [comment]
This LGTM, thanks for the updates. I can work on publishing changes later today.

**Comment by seletz** [comment]
@TattdCodeMonkey thanks for merging!

**Comment by TattdCodeMonkey** [comment]
@seletz  this is now released to hex. Thanks for the PR

**Pull request merged**
